name: RealTimeMod NeoForge - Feature Request
description: Share Suggestion or Feature Request!
assignees: "NorthWestTreesgaming"
title: "[Feature] <title>"
labels: [New, Feature]
body:
- type: textarea
  attributes:
    label: Suggestion/Feature Description
    description: |
      - *(REQUIRED)*
      Describe the suggestion or feature here. 
      *Example:* Add a 7-day forecast and weather system.
    placeholder: Describe the suggestion or feature here. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Attachments
    description: |
      - *(OPTIONAL)*
      You can also drag and drop images here to share them as examples.
    placeholder: Drag and drop the files here.
  validations:
    required: false
